#!/usr/bin/env python

"""Example of program with many options using docopt.
Usage:
  cloudsteak --version
  cloudsteak aws --name NAME
  cloudsteak aws -n NAME
  cloudsteak azure --name NAME
  cloudsteak azure -n NAME
Arguments:
  PATH  destination path
Options:
  -h --help            show this help message and exit
  -v --version         show version and exit
  --verbose            print status messages
  -q --quiet           report only file names
  -r --repeat          show all occurrences of the same error
  -n --name            show name and exit
"""



from docopt import docopt

## Version of the current package
from bin.version import __version__

if __name__ == '__main__':
  name = docopt(__doc__)["NAME"]
   
  if docopt(__doc__)["--name"] and docopt(__doc__)["aws"]:
    print("AWS name: {0}".format(name))

  if docopt(__doc__)["--name"] and docopt(__doc__)["azure"]:
    print("Azure name: {0}".format(name))

  arguments = docopt(__doc__, version=__version__)
  print(arguments)